title: INF-161 Diseño y Administración de Base de Datos - 12 REGLAS DE CODD
iconURL: assets/default-icon.png
remote_theme: supunkavinda/jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N